# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a9c08e281141ff1eabb6d6ed30a76b19"
name = "timer-app"
handle = "timer-app-17"
application_url = "https://floral-missions-advertise-richard.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "timer15.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://floral-missions-advertise-richard.trycloudflare.com/auth/callback",
  "https://floral-missions-advertise-richard.trycloudflare.com/auth/shopify/callback",
  "https://floral-missions-advertise-richard.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
